name: modelcard-action
description: Relative path from the project root to the target model card .yaml file
inputs:
  modelcard:
    description: Modelcard file to be analyzed
    type: string
    required: true
    default: modelcard.yaml
  rules:
    description: Relative path to the folder containing custom rules
    type: string
    require: false
  disable_default_rules:
    description: If set to true and custom rules are defined, completely disables all default rules
    require: false
    type: boolean
runs:
  using: docker
  image: 'docker://ghcr.io/compliancepal/modelcard-action'
  args:
    - ${{ inputs.modelcard }}
    - ${{ inputs.rules }}
    - ${{ inputs.disable_default_rules }}
