name: modelcard-action
description: Relative path from the project root to the target model card .yaml file
inputs:
  modelcard:
    description: Modelcard file to be analyzed
    required: true
    default: modelcard.yaml
  rules:
    description: Relative path to the folder containing custom rules
    require: false
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.modelcard }}
    - ${{ inputs.rules }}
    - ${{ inputs.disable_default }}
