name: modelcard-test

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  file-exists:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install yaml parser
        run: npm install js-yaml

      - name: Check MLproject file exists
        run: node .github/scripts/modelcard-check.js
      
