name: Release new action version
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      TAG_NAME:
        description: 'Tag name that the major tag will point to'
        required: true

env:
  TAG_NAME: ${{ github.event.inputs.TAG_NAME }}

jobs:
  update-major-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Set output
        id: meta
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Update the ${{ env.TAG_NAME || steps.meta.outputs.tag }} tag
        uses: actions/publish-action@v0.2.0
        with:
          source-tag: ${{ env.TAG_NAME || steps.meta.outputs.tag }}
